"""Tests for the shape registry + Quick Draw! variant integration."""

from __future__ import annotations

import pytest

from shapes import SHAPE_VARIANTS, SHAPES


class TestShapeRegistry:
    def test_canonical_outlines_exist_for_all_animals(self):
        # Plan §0 names five animals; the registry must cover all of them.
        expected = {"pig", "cat", "dog", "dino", "chicken"}
        assert expected.issubset(SHAPES.keys())

    def test_all_canonical_outlines_have_enough_points(self):
        # Plan §3.3: 30-50 waypoints per outline. Allow 15+ as the floor —
        # some hand-authored shapes are sparser before resampling.
        for name, outline in SHAPES.items():
            assert len(outline) >= 15, f"{name} has only {len(outline)} points"

    def test_shape_variants_keys_match_shapes(self):
        assert set(SHAPE_VARIANTS.keys()) == set(SHAPES.keys())

    def test_first_variant_is_canonical(self):
        # Convention: SHAPE_VARIANTS[name][0] is the hand-authored canonical
        # outline (so legacy callers can index 0 to get the original).
        for name in SHAPES:
            assert SHAPE_VARIANTS[name][0] is SHAPES[name]

    def test_quickdraw_variants_present_when_module_exists(self):
        """The Quick Draw variant module is generated by tools/
        quickdraw_to_shape.py. When it's been generated for a category,
        SHAPE_VARIANTS gains additional outlines beyond the canonical."""
        # We don't pin the count (regeneration may change it) — just check
        # that at least one animal has more than the single canonical.
        any_extra = any(len(v) > 1 for v in SHAPE_VARIANTS.values())
        # Skip rather than fail when the curation hasn't been run yet — CI
        # without the data will still see a valid registry.
        if not any_extra:
            pytest.skip("No Quick Draw variants generated; run "
                        "`python tools/quickdraw_to_shape.py`")
        assert any_extra

    def test_all_variants_are_lists_of_xy_tuples(self):
        for name, variants in SHAPE_VARIANTS.items():
            for i, outline in enumerate(variants):
                assert isinstance(outline, list), f"{name}[{i}] not a list"
                for pt in outline[:3]:  # spot-check first few
                    assert len(pt) == 2, f"{name}[{i}] has non-XY point {pt!r}"
                    assert isinstance(pt[0], float)
                    assert isinstance(pt[1], float)
