"""Cat outline — converted from a public-domain sitting-cat silhouette SVG.

Source SVG: Wikimedia Commons: Cat silhouette (public domain).
License: public domain (Wikimedia Commons).

Sitting cat in side profile. Two pointy ears + curling tail = cat. The sitting pose gives it a tall distinctive shape that survives street snapping.

Generated by `tools/svg_to_shape.py` (sampled by arc length, simplified
with Ramer-Douglas-Peucker, y-flipped from SVG y-down to math y-up).
Hand-edits welcome — this file is the source of truth, regeneration is
not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

CAT_OUTLINE: List[Point] = [
    (4.06, 2.10),
    (8.33, 2.10),
    (8.23, 2.70),
    (7.35, 2.92),
    (8.02, 4.11),
    (8.55, 4.50),
    (9.13, 4.23),
    (9.35, 3.23),
    (9.95, 2.41),
    (10.51, 2.02),
    (10.97, 2.10),
    (11.05, 2.58),
    (10.20, 3.83),
    (10.11, 5.02),
    (10.41, 6.34),
    (11.65, 8.16),
    (11.48, 10.01),
    (12.00, 11.05),
    (11.50, 13.16),
    (10.09, 12.33),
    (8.51, 12.75),
    (8.80, 9.79),
    (6.36, 9.09),
    (5.08, 8.26),
    (4.01, 6.73),
    (2.94, 3.68),
    (0.00, 1.71),
    (0.01, 0.58),
    (1.18, 0.00),
    (0.70, 0.79),
    (0.94, 1.38),
    (3.29, 2.37),
    (4.06, 2.10),
    (4.06, 2.10),
]
