"""Cat outline — derived from a kawaii cartoon-cat SVG.

Source SVG: freesvg.org "Cute Cat Vector Image" (https://freesvg.org/cute-cat-vector-image).
License: public domain (CC0 / freesvg.org).

Classic kawaii cat: round head/body fused into one chubby blob, two pointy
triangle ears on top, curled tail off the back. Generated via shapely-union
of body + head + ears + tail sub-paths.

Generated by `tools/svg_to_shape.py --mode union` (or single, depending
on the source SVG). The shape file is the source of truth — hand edits
welcome — regeneration is not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

CAT_OUTLINE: List[Point] = [
    (8.62, 7.25),
    (9.59, 8.20),
    (10.26, 8.35),
    (10.72, 7.72),
    (11.13, 6.39),
    (11.75, 5.35),
    (12.00, 4.18),
    (11.96, 2.72),
    (11.63, 1.57),
    (11.02, 0.75),
    (9.60, 0.17),
    (7.63, 0.00),
    (5.68, 0.30),
    (4.89, 0.63),
    (4.45, 1.02),
    (3.12, 0.46),
    (2.03, 0.27),
    (1.15, 0.42),
    (0.49, 0.91),
    (0.00, 2.12),
    (0.04, 2.46),
    (0.30, 2.67),
    (0.85, 2.64),
    (1.62, 2.33),
    (1.97, 1.50),
    (2.46, 1.14),
    (3.15, 1.17),
    (4.08, 1.63),
    (3.73, 3.11),
    (3.83, 4.82),
    (4.18, 5.79),
    (4.69, 6.47),
    (5.08, 7.68),
    (5.52, 8.32),
    (5.80, 8.39),
    (6.19, 8.22),
    (7.20, 7.24),
    (8.62, 7.25),
]
