"""Cat candidate 4 — Cat face — big triangular ears, eyes, nose, whiskers

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (1.500, 6.500),
    (2.000, 11.000),
    (4.500, 7.500),
    (6.000, 7.800),
    (7.500, 7.500),
    (10.000, 11.000),
    (10.500, 6.500),
    (10.078, 6.402),
    (10.308, 5.800),
    (10.450, 5.171),
    (10.500, 4.528),
    (10.458, 3.885),
    (10.324, 3.254),
    (10.102, 2.649),
    (9.795, 2.082),
    (9.411, 1.565),
    (8.956, 1.107),
    (8.441, 0.720),
    (7.876, 0.410),
    (7.273, 0.184),
    (6.643, 0.046),
    (6.000, 0.000),
    (6.000, 0.000),
    (6.000, 0.000),
    (5.357, 0.046),
    (4.727, 0.184),
    (4.124, 0.410),
    (3.559, 0.720),
    (3.044, 1.107),
    (2.589, 1.565),
    (2.205, 2.082),
    (1.898, 2.649),
    (1.676, 3.254),
    (1.542, 3.885),
    (1.500, 4.528),
    (1.550, 5.171),
    (1.692, 5.800),
    (1.922, 6.402),
    (1.500, 6.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (4.900, 5.500),
        (4.824, 5.735),
        (4.624, 5.880),
        (4.376, 5.880),
        (4.176, 5.735),
        (4.100, 5.500),
        (4.176, 5.265),
        (4.376, 5.120),
        (4.624, 5.120),
        (4.824, 5.265),
        (4.900, 5.500),
    ],
    [
        (7.900, 5.500),
        (7.824, 5.735),
        (7.624, 5.880),
        (7.376, 5.880),
        (7.176, 5.735),
        (7.100, 5.500),
        (7.176, 5.265),
        (7.376, 5.120),
        (7.624, 5.120),
        (7.824, 5.265),
        (7.900, 5.500),
    ],
    [
        (5.700, 4.200),
        (6.300, 4.200),
        (6.000, 3.700),
        (6.000, 4.000),
    ],
    [
        (1.500, 3.800),
    ],
    [
        (1.500, 3.000),
    ],
    [
        (1.500, 2.200),
    ],
    [
        (10.500, 3.800),
    ],
    [
        (10.500, 3.000),
    ],
    [
        (10.500, 2.200),
    ],
]

METADATA = {"description": 'Cat face — big triangular ears, eyes, nose, whiskers', "source": "hand-crafted by tools/gen_candidates.py"}
