"""Cat candidate 2 — Cat face — pointy ears, whiskers, nose triangle

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (2.500, 7.000),
    (2.000, 9.500),
    (4.000, 7.500),
    (6.000, 8.000),
    (8.000, 7.500),
    (10.000, 9.500),
    (9.500, 7.000),
    (9.897, 7.250),
    (10.229, 6.539),
    (10.432, 5.781),
    (10.500, 5.000),
    (10.432, 4.219),
    (10.229, 3.461),
    (9.897, 2.750),
    (9.447, 2.107),
    (8.893, 1.553),
    (8.250, 1.103),
    (7.539, 0.771),
    (6.781, 0.568),
    (6.000, 0.500),
    (6.000, 0.500),
    (6.000, 0.500),
    (5.219, 0.568),
    (4.461, 0.771),
    (3.750, 1.103),
    (3.107, 1.553),
    (2.553, 2.107),
    (2.103, 2.750),
    (1.771, 3.461),
    (1.568, 4.219),
    (1.500, 5.000),
    (1.568, 5.781),
    (1.771, 6.539),
    (2.103, 7.250),
    (2.500, 7.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (5.700, 4.800),
        (6.300, 4.800),
        (6.000, 4.500),
        (6.000, 5.000),
    ],
    [
        (2.000, 4.800),
    ],
    [
        (2.000, 4.000),
    ],
    [
        (2.000, 3.200),
    ],
    [
        (10.000, 4.800),
    ],
    [
        (10.000, 4.000),
    ],
    [
        (10.000, 3.200),
    ],
]

METADATA = {"description": 'Cat face — pointy ears, whiskers, nose triangle', "source": "hand-crafted by tools/gen_candidates.py"}
