"""Cat candidate 3 — Sitting cat — arched back, vertical curled tail, eye dot

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (10.000, 7.000),
    (10.500, 8.000),
    (11.000, 7.000),
    (11.500, 6.500),
    (11.800, 5.800),
    (11.200, 5.500),
    (10.800, 5.200),
    (10.500, 3.000),
    (10.500, 0.500),
    (9.500, 0.500),
    (9.500, 2.500),
    (6.000, 1.500),
    (4.000, 0.500),
    (3.000, 0.500),
    (3.000, 2.500),
    (2.500, 4.500),
    (1.500, 5.000),
    (1.000, 7.000),
    (1.500, 8.500),
    (2.500, 8.200),
    (2.800, 7.000),
    (2.000, 6.500),
    (1.800, 6.800),
    (2.000, 7.500),
    (2.500, 6.000),
    (4.000, 6.500),
    (6.000, 6.800),
    (8.000, 6.800),
    (9.500, 6.700),
    (9.500, 7.800),
    (10.000, 7.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (11.400, 6.500),
        (11.400, 6.300),
        (11.200, 6.400),
    ],
]

METADATA = {"description": 'Sitting cat — arched back, vertical curled tail, eye dot', "source": "hand-crafted by tools/gen_candidates.py"}
