"""Cat candidate 5 — Walking cat — long body, tail straight up, head forward

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (12.000, 4.000),
    (12.000, 4.800),
    (11.000, 5.000),
    (10.700, 5.300),
    (10.200, 6.500),
    (9.800, 5.300),
    (9.400, 5.400),
    (9.000, 6.500),
    (8.700, 5.300),
    (6.000, 5.400),
    (3.000, 5.400),
    (2.000, 5.500),
    (1.500, 7.500),
    (1.200, 8.500),
    (2.000, 8.500),
    (2.200, 7.500),
    (2.500, 5.500),
    (3.000, 4.500),
    (3.000, 3.000),
    (3.000, 0.500),
    (3.000, 0.200),
    (4.000, 0.200),
    (4.000, 0.500),
    (4.000, 2.000),
    (6.000, 2.000),
    (9.000, 2.000),
    (9.000, 0.500),
    (9.000, 0.200),
    (10.000, 0.200),
    (10.000, 0.500),
    (10.000, 2.000),
    (10.500, 3.000),
    (11.000, 3.600),
    (11.500, 3.800),
    (12.000, 4.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (10.700, 4.700),
        (10.700, 4.500),
        (10.500, 4.600),
    ],
    [
        (11.700, 4.600),
    ],
    [
        (11.700, 4.200),
    ],
    [
        (11.700, 3.800),
    ],
]

METADATA = {"description": 'Walking cat — long body, tail straight up, head forward', "source": "hand-crafted by tools/gen_candidates.py"}
