"""Chicken candidate 3 — Sitting hen — egg-like body, small comb, wing loop

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (9.000, 7.000),
    (9.000, 7.800),
    (9.500, 7.000),
    (9.700, 7.800),
    (10.200, 7.000),
    (10.700, 6.500),
    (11.500, 6.000),
    (12.300, 5.600),
    (11.200, 5.300),
    (10.500, 4.500),
    (10.432, 2.719),
    (10.212, 1.915),
    (9.847, 1.166),
    (9.351, 0.496),
    (8.739, -0.070),
    (8.034, -0.514),
    (7.259, -0.820),
    (6.441, -0.978),
    (5.608, -0.983),
    (4.788, -0.834),
    (4.010, -0.536),
    (3.300, -0.100),
    (2.682, 0.460),
    (2.179, 1.124),
    (1.806, 1.869),
    (1.577, 2.670),
    (1.500, 3.500),
    (2.000, 4.500),
    (2.500, 6.000),
    (4.000, 7.000),
    (6.000, 7.500),
    (8.000, 7.300),
    (9.000, 7.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (10.700, 6.100),
        (10.700, 5.900),
        (10.500, 6.000),
    ],
    [
        (5.000, 5.500),
        (7.000, 5.500),
        (6.000, 4.500),
    ],
]

METADATA = {"description": 'Sitting hen — egg-like body, small comb, wing loop', "source": "hand-crafted by tools/gen_candidates.py"}
