"""Chicken candidate 4 — Round chick — full circle body, two legs, tiny wing

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (5.000, 9.000),
    (5.000, 9.000),
    (5.670, 8.943),
    (6.321, 8.776),
    (6.935, 8.501),
    (7.494, 8.127),
    (7.983, 7.665),
    (8.387, 7.128),
    (8.696, 6.531),
    (8.900, 5.890),
    (8.994, 5.224),
    (8.975, 4.552),
    (8.844, 3.893),
    (8.604, 3.264),
    (8.262, 2.685),
    (7.828, 2.172),
    (9.200, 3.800),
    (10.500, 3.000),
    (9.200, 2.200),
    (7.571, 1.936),
    (7.000, 1.536),
    (6.368, 1.241),
    (5.695, 1.061),
    (5.000, 1.000),
    (4.305, 1.061),
    (3.632, 1.241),
    (3.000, 1.536),
    (2.429, 1.936),
    (4.500, 1.000),
    (4.500, 0.000),
    (4.800, -0.200),
    (4.800, 1.000),
    (5.500, 1.000),
    (5.500, 0.000),
    (5.800, -0.200),
    (5.800, 1.000),
    (1.936, 2.429),
    (1.561, 2.957),
    (1.277, 3.539),
    (1.089, 4.159),
    (1.005, 4.801),
    (1.025, 5.448),
    (1.150, 6.083),
    (1.375, 6.690),
    (1.695, 7.253),
    (2.102, 7.757),
    (2.585, 8.189),
    (3.131, 8.536),
    (3.726, 8.792),
    (4.355, 8.948),
    (5.000, 9.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (7.300, 5.500),
        (7.243, 5.676),
        (7.093, 5.785),
        (6.907, 5.785),
        (6.757, 5.676),
        (6.700, 5.500),
        (6.757, 5.324),
        (6.907, 5.215),
        (7.093, 5.215),
        (7.243, 5.324),
        (7.300, 5.500),
    ],
    [
        (3.500, 4.000),
        (3.500, 5.500),
        (5.000, 4.500),
    ],
]

METADATA = {"description": 'Round chick — full circle body, two legs, tiny wing', "source": "hand-crafted by tools/gen_candidates.py"}
