"""Chicken outline — converted from a public-domain rooster silhouette SVG.

Source SVG: Wikimedia Commons: Rooster silhouette 02 (LadyofHats, public domain).
License: public domain (Wikimedia Commons).

Rooster in side profile. Plump round body, tail feathers fanning back, small head with beak forward.

Generated by `tools/svg_to_shape.py` (sampled by arc length, simplified
with Ramer-Douglas-Peucker, y-flipped from SVG y-down to math y-up).
Hand-edits welcome — this file is the source of truth, regeneration is
not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

CHICKEN_OUTLINE: List[Point] = [
    (12.00, 9.95),
    (11.59, 10.47),
    (10.95, 10.74),
    (9.43, 10.33),
    (8.35, 9.44),
    (6.95, 7.59),
    (5.80, 6.79),
    (4.85, 7.49),
    (4.39, 7.26),
    (3.40, 7.82),
    (2.23, 8.00),
    (1.08, 7.78),
    (0.00, 6.70),
    (0.02, 6.51),
    (0.69, 6.53),
    (0.78, 6.35),
    (0.45, 5.26),
    (0.42, 3.86),
    (0.97, 2.09),
    (1.54, 1.36),
    (1.74, 1.25),
    (1.18, 1.90),
    (0.78, 2.99),
    (0.93, 5.29),
    (1.41, 3.19),
    (2.33, 1.86),
    (1.78, 3.37),
    (1.68, 4.56),
    (2.55, 3.87),
    (3.79, 3.27),
    (3.50, 3.61),
    (3.50, 4.07),
    (4.32, 3.71),
    (4.53, 4.06),
    (4.99, 3.54),
    (4.95, 3.69),
    (5.33, 3.53),
    (5.89, 3.03),
    (6.37, 2.99),
    (7.32, 2.38),
    (7.40, 1.68),
    (7.14, 1.36),
    (7.35, 1.04),
    (7.17, 0.42),
    (7.94, 0.00),
    (7.99, 0.25),
    (7.81, 0.36),
    (9.19, 0.24),
    (8.89, 0.50),
    (7.97, 0.60),
    (8.24, 0.91),
    (7.69, 0.81),
    (7.86, 2.13),
    (7.93, 1.71),
    (8.15, 1.78),
    (8.34, 1.45),
    (8.38, 0.78),
    (8.55, 1.54),
    (8.84, 0.88),
    (8.95, 0.98),
    (8.84, 1.66),
    (7.92, 2.63),
    (8.27, 3.23),
    (10.14, 4.95),
    (10.89, 6.66),
    (10.77, 8.04),
    (10.99, 9.41),
    (11.26, 9.79),
    (12.00, 9.95),
    (12.00, 9.95),
]
