"""Chicken candidate 2 — Chicken head — jagged comb, beak, wattle, eye

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (3.000, 8.000),
    (3.500, 9.500),
    (4.500, 8.500),
    (5.000, 10.000),
    (6.000, 8.500),
    (6.500, 10.200),
    (7.500, 8.500),
    (8.000, 9.500),
    (8.500, 8.000),
    (7.928, 7.798),
    (8.229, 7.507),
    (8.487, 7.178),
    (8.696, 6.815),
    (8.853, 6.427),
    (8.954, 6.021),
    (8.998, 5.605),
    (8.984, 5.186),
    (8.911, 4.774),
    (8.782, 4.376),
    (8.598, 4.000),
    (9.500, 4.500),
    (11.500, 4.000),
    (9.500, 3.500),
    (9.000, 3.300),
    (9.500, 2.500),
    (9.000, 1.500),
    (8.500, 2.000),
    (8.500, 3.000),
    (9.000, 3.300),
    (8.598, 4.000),
    (8.270, 3.538),
    (7.861, 3.147),
    (7.385, 2.839),
    (6.860, 2.626),
    (6.305, 2.516),
    (5.739, 2.511),
    (5.181, 2.614),
    (4.654, 2.819),
    (4.174, 3.120),
    (3.759, 3.506),
    (3.424, 3.962),
    (3.181, 4.474),
    (3.000, 6.500),
    (3.000, 8.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (7.300, 6.500),
        (7.243, 6.676),
        (7.093, 6.785),
        (6.907, 6.785),
        (6.757, 6.676),
        (6.700, 6.500),
        (6.757, 6.324),
        (6.907, 6.215),
        (7.093, 6.215),
        (7.243, 6.324),
        (7.300, 6.500),
    ],
]

METADATA = {"description": 'Chicken head — jagged comb, beak, wattle, eye', "source": "hand-crafted by tools/gen_candidates.py"}
