"""Chicken candidate 5 — Crowing rooster — head back, open beak, dramatic plumes

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (10.500, 9.500),
    (11.500, 8.500),
    (10.500, 8.000),
    (11.000, 7.000),
    (11.500, 6.000),
    (10.500, 5.500),
    (10.000, 6.500),
    (10.500, 7.000),
    (11.000, 7.000),
    (9.500, 6.000),
    (8.500, 5.000),
    (8.500, 3.000),
    (9.000, 0.500),
    (9.500, 0.500),
    (9.500, 0.200),
    (10.000, 0.200),
    (10.000, 0.500),
    (10.500, 1.000),
    (10.000, 2.500),
    (6.000, 2.000),
    (5.000, 0.500),
    (4.500, 0.500),
    (4.500, 0.200),
    (4.000, 0.200),
    (4.000, 0.500),
    (3.500, 1.000),
    (4.000, 2.500),
    (2.500, 3.000),
    (1.500, 3.500),
    (0.500, 4.500),
    (0.000, 6.500),
    (1.000, 8.500),
    (1.500, 7.500),
    (2.000, 9.000),
    (2.500, 7.500),
    (3.000, 9.000),
    (3.500, 7.000),
    (4.000, 6.000),
    (5.000, 6.000),
    (6.500, 6.500),
    (7.500, 7.000),
    (8.000, 8.000),
    (8.500, 9.500),
    (9.000, 8.500),
    (9.500, 9.700),
    (10.000, 9.000),
    (10.500, 9.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (9.200, 8.100),
        (9.200, 7.900),
        (9.000, 8.000),
    ],
]

METADATA = {"description": 'Crowing rooster — head back, open beak, dramatic plumes', "source": "hand-crafted by tools/gen_candidates.py"}
