"""Dino candidate 2 — T-rex — big head, tiny arm, thick tail, teeth

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (14.000, 6.500),
    (14.000, 7.500),
    (12.500, 8.000),
    (11.500, 7.500),
    (10.500, 6.500),
    (9.500, 6.000),
    (7.500, 6.200),
    (5.000, 5.800),
    (3.000, 5.000),
    (1.500, 4.400),
    (0.300, 4.000),
    (0.300, 3.600),
    (1.500, 3.600),
    (3.000, 3.400),
    (5.000, 3.000),
    (6.000, 2.500),
    (6.500, 1.500),
    (5.800, 0.400),
    (5.800, 0.200),
    (7.500, 0.200),
    (7.500, 0.400),
    (7.200, 1.500),
    (8.500, 2.500),
    (9.500, 3.500),
    (10.000, 3.000),
    (10.500, 3.200),
    (10.000, 3.500),
    (9.500, 3.500),
    (10.000, 4.500),
    (10.500, 5.500),
    (11.500, 6.000),
    (12.500, 6.300),
    (13.500, 6.400),
    (14.000, 6.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (13.300, 6.200),
        (13.100, 6.500),
        (12.900, 6.200),
        (12.700, 6.500),
    ],
    [
        (12.700, 7.500),
        (12.700, 7.300),
        (12.500, 7.400),
    ],
]

METADATA = {"description": 'T-rex — big head, tiny arm, thick tail, teeth', "source": "hand-crafted by tools/gen_candidates.py"}
