"""Dinosaur outline — derived from a kawaii cute-dinosaur SVG.

Source SVG: freesvg.org "Cute Dinosaur" (https://freesvg.org/cute-dinosaur).
License: public domain (CC0 / freesvg.org).

Kawaii baby T-rex: round body, dorsal spike bumps along the top, tiny legs at the bottom, head+tail bumps on left and right. Generated via shapely-union of body + head + tail + spikes + leg sub-paths into one continuous silhouette.

Generated by `tools/svg_to_shape.py --mode union` (or single, depending
on the source SVG). The shape file is the source of truth — hand edits
welcome — regeneration is not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

DINO_OUTLINE: List[Point] = [
    (0.21, 10.12),
    (0.00, 8.16),
    (0.34, 6.51),
    (1.13, 5.34),
    (2.52, 4.46),
    (1.48, 3.99),
    (1.05, 3.00),
    (1.34, 1.93),
    (2.35, 0.36),
    (2.66, 0.29),
    (3.67, 1.38),
    (4.22, 1.64),
    (4.30, 2.16),
    (5.50, 1.65),
    (7.33, 1.64),
    (7.29, 0.76),
    (7.65, 0.33),
    (8.73, 0.00),
    (9.53, 0.17),
    (9.72, 1.52),
    (10.75, 2.77),
    (11.25, 4.94),
    (10.89, 9.64),
    (12.00, 13.66),
    (11.97, 14.32),
    (11.33, 14.20),
    (9.66, 13.04),
    (9.10, 13.44),
    (8.02, 13.42),
    (8.19, 14.62),
    (7.72, 15.03),
    (6.70, 14.93),
    (5.43, 14.22),
    (4.28, 15.09),
    (2.92, 15.05),
    (1.82, 14.07),
    (1.67, 13.19),
    (0.73, 11.71),
    (0.21, 10.12),
]
