"""Dino candidate 5 — Pterodactyl — spread wings, crest, sharp beak

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (6.000, 7.500),
    (6.000, 8.500),
    (5.500, 9.000),
    (4.500, 10.000),
    (4.000, 8.500),
    (4.500, 8.000),
    (4.000, 7.500),
    (1.000, 7.000),
    (-1.000, 8.000),
    (-2.000, 7.500),
    (-1.000, 7.000),
    (1.000, 6.500),
    (3.000, 6.000),
    (4.000, 5.500),
    (4.000, 4.000),
    (4.500, 3.500),
    (5.500, 4.000),
    (5.500, 5.500),
    (6.500, 6.000),
    (8.500, 6.500),
    (10.500, 7.000),
    (13.000, 8.000),
    (14.000, 7.500),
    (13.000, 7.000),
    (10.500, 7.000),
    (8.500, 7.300),
    (6.500, 7.500),
    (6.000, 8.000),
    (6.000, 7.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (5.700, 8.300),
        (5.700, 8.100),
        (5.500, 8.200),
    ],
]

METADATA = {"description": 'Pterodactyl — spread wings, crest, sharp beak', "source": "hand-crafted by tools/gen_candidates.py"}
