"""Dinosaur outline — converted from a public-domain T-Rex silhouette SVG.

Source SVG: Wikimedia Commons: Tyrannosaurus silhouette (public domain).
License: public domain (Wikimedia Commons).

T-Rex silhouette — the viral GPS-art animal. Big head, TINY arms (the chest-level bumps), big legs, long tapering tail. Tiny arms are the signature feature.

Generated by `tools/svg_to_shape.py` (sampled by arc length, simplified
with Ramer-Douglas-Peucker, y-flipped from SVG y-down to math y-up).
Hand-edits welcome — this file is the source of truth, regeneration is
not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

DINO_OUTLINE: List[Point] = [
    (5.69, 0.06),
    (5.75, 0.95),
    (6.69, 2.32),
    (2.74, 3.46),
    (0.00, 2.93),
    (0.04, 3.08),
    (2.43, 3.91),
    (5.07, 3.54),
    (8.50, 4.04),
    (9.68, 3.87),
    (10.38, 4.24),
    (11.13, 3.98),
    (11.96, 3.33),
    (12.00, 3.07),
    (11.79, 2.93),
    (11.11, 3.14),
    (11.54, 2.41),
    (11.31, 2.28),
    (10.34, 3.14),
    (9.87, 2.90),
    (9.62, 2.45),
    (10.09, 2.36),
    (10.27, 2.12),
    (9.48, 2.22),
    (9.61, 1.72),
    (9.07, 2.30),
    (8.31, 2.14),
    (7.99, 1.41),
    (8.62, 0.99),
    (8.58, 0.13),
    (8.38, 0.22),
    (8.24, 0.86),
    (7.70, 1.22),
    (7.55, 1.97),
    (6.31, 1.26),
    (5.88, 0.31),
    (6.19, 0.00),
    (5.69, 0.06),
]
