"""Dino candidate 3 — Triceratops face — three horns, bumpy frill

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (10.000, 4.500),
    (10.500, 4.000),
    (10.000, 3.000),
    (9.000, 2.500),
    (9.500, 2.000),
    (8.500, 1.500),
    (7.000, 1.000),
    (4.500, 1.500),
    (2.500, 3.000),
    (2.000, 4.500),
    (1.500, 5.500),
    (0.500, 7.000),
    (1.500, 8.000),
    (2.500, 8.500),
    (3.000, 9.500),
    (3.500, 8.500),
    (4.500, 9.700),
    (5.500, 8.500),
    (6.500, 9.700),
    (7.500, 8.500),
    (8.500, 9.500),
    (9.000, 8.500),
    (10.000, 8.000),
    (11.000, 7.000),
    (10.500, 5.500),
    (10.000, 4.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (5.800, 5.500),
        (6.200, 5.500),
        (6.000, 4.000),
    ],
    [
        (3.500, 7.500),
        (4.500, 7.500),
        (4.000, 5.000),
    ],
    [
        (7.500, 7.500),
        (8.500, 7.500),
        (8.000, 5.000),
    ],
    [
        (4.700, 4.300),
        (4.700, 4.100),
        (4.500, 4.200),
    ],
    [
        (7.700, 4.300),
        (7.700, 4.100),
        (7.500, 4.200),
    ],
]

METADATA = {"description": 'Triceratops face — three horns, bumpy frill', "source": "hand-crafted by tools/gen_candidates.py"}
