"""Dino candidate 4 — Stegosaurus — five plates, thagomizer spikes

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (13.000, 4.000),
    (13.500, 4.500),
    (13.000, 5.000),
    (11.500, 4.800),
    (10.500, 5.000),
    (10.000, 5.000),
    (9.800, 6.500),
    (9.500, 7.000),
    (9.200, 6.500),
    (9.000, 5.000),
    (8.500, 5.000),
    (8.300, 7.500),
    (8.000, 8.000),
    (7.700, 7.500),
    (7.500, 5.000),
    (7.000, 5.000),
    (6.800, 8.000),
    (6.500, 8.500),
    (6.200, 8.000),
    (6.000, 5.000),
    (5.500, 5.000),
    (5.300, 7.500),
    (5.000, 8.000),
    (4.700, 7.500),
    (4.500, 5.000),
    (4.000, 5.000),
    (3.800, 6.500),
    (3.500, 7.000),
    (3.200, 6.500),
    (3.000, 5.000),
    (2.500, 4.800),
    (1.500, 4.500),
    (1.000, 5.500),
    (0.700, 5.000),
    (1.000, 4.400),
    (0.500, 5.300),
    (0.200, 4.800),
    (0.200, 4.200),
    (0.200, 3.800),
    (1.500, 3.800),
    (3.000, 3.600),
    (4.000, 3.000),
    (4.500, 2.500),
    (4.500, 0.400),
    (4.500, 0.200),
    (6.000, 0.200),
    (6.000, 0.400),
    (5.800, 2.400),
    (8.000, 2.400),
    (10.000, 2.400),
    (10.500, 2.400),
    (10.500, 0.400),
    (10.500, 0.200),
    (12.000, 0.200),
    (12.000, 0.400),
    (11.800, 2.500),
    (12.300, 3.200),
    (12.700, 3.700),
    (13.000, 4.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
]

METADATA = {"description": 'Stegosaurus — five plates, thagomizer spikes', "source": "hand-crafted by tools/gen_candidates.py"}
