"""Dog outline — derived from a geometric kawaii dog-icon SVG.

Source SVG: freesvg.org "Dog Icon" (https://freesvg.org/dog-icon).
License: public domain (CC0 / freesvg.org).

Blocky cartoon dog with a chunky body, four short legs and a rounded head with a small ear bump. Single-path SVG so we trace the largest non-bg sub-path directly.

Generated by `tools/svg_to_shape.py --mode union` (or single, depending
on the source SVG). The shape file is the source of truth — hand edits
welcome — regeneration is not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

DOG_OUTLINE: List[Point] = [
    (4.75, 12.02),
    (2.96, 11.70),
    (2.18, 10.79),
    (2.00, 10.00),
    (1.92, 5.12),
    (1.48, 4.22),
    (0.53, 3.90),
    (0.10, 3.48),
    (0.00, 0.85),
    (0.18, 0.28),
    (0.70, 0.00),
    (1.92, 0.00),
    (1.97, 0.94),
    (1.50, 1.52),
    (1.54, 2.50),
    (2.92, 2.78),
    (3.78, 0.16),
    (5.97, 0.02),
    (5.87, 1.19),
    (5.00, 1.58),
    (5.00, 4.02),
    (8.46, 4.02),
    (9.23, 1.31),
    (9.71, 0.42),
    (10.41, 0.03),
    (11.83, 0.02),
    (12.00, 0.06),
    (11.95, 1.07),
    (11.00, 1.63),
    (11.02, 5.66),
    (7.97, 8.02),
    (3.50, 8.03),
    (3.54, 10.26),
    (3.85, 10.50),
    (5.06, 10.59),
    (5.46, 11.03),
    (5.41, 11.62),
    (4.75, 12.02),
    (4.75, 12.02),
]
