"""Dog candidate 5 — Running dog — action pose, legs spread, tail up

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (13.000, 3.500),
    (13.000, 4.300),
    (12.000, 4.500),
    (11.500, 5.000),
    (10.500, 5.300),
    (9.500, 6.500),
    (9.000, 5.500),
    (10.000, 5.000),
    (9.000, 5.700),
    (6.000, 5.600),
    (4.000, 5.400),
    (3.000, 5.500),
    (2.000, 7.000),
    (1.500, 8.000),
    (2.300, 8.200),
    (2.800, 7.000),
    (3.500, 5.400),
    (4.000, 5.000),
    (4.000, 3.500),
    (2.500, 1.500),
    (2.000, 1.000),
    (2.500, 0.500),
    (3.500, 1.500),
    (4.500, 2.500),
    (7.000, 1.800),
    (9.000, 1.500),
    (10.500, 0.500),
    (11.500, 0.800),
    (10.800, 1.800),
    (9.800, 2.200),
    (11.000, 2.500),
    (11.700, 3.000),
    (12.300, 3.300),
    (13.000, 3.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (12.000, 2.800),
        (12.400, 2.600),
        (12.700, 3.000),
        (12.500, 3.500),
    ],
    [
        (11.200, 4.800),
        (11.200, 4.600),
        (11.000, 4.700),
    ],
]

METADATA = {"description": 'Running dog — action pose, legs spread, tail up', "source": "hand-crafted by tools/gen_candidates.py"}
