"""Dog outline — converted from a public-domain standing-dog silhouette SVG.

Source SVG: Wikimedia Commons: Dog Silhouette 01 (public domain).
License: public domain (Wikimedia Commons).

Standing dog in side profile, FACING RIGHT (x-flipped from source SVG which faced left). Curly tail held UP at the back; one floppy ear silhouette.

Generated by `tools/svg_to_shape.py` (sampled by arc length, simplified
with Ramer-Douglas-Peucker, y-flipped from SVG y-down to math y-up, x-flipped to face right).
Hand-edits welcome — this file is the source of truth, regeneration is
not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

DOG_OUTLINE: List[Point] = [
    (6.88, 0.00),
    (7.00, 0.22),
    (6.44, 1.11),
    (6.55, 3.29),
    (6.80, 4.35),
    (7.51, 5.17),
    (7.69, 4.54),
    (9.17, 2.25),
    (9.91, 0.57),
    (10.27, 0.16),
    (10.75, 0.16),
    (10.84, 0.40),
    (10.16, 1.24),
    (9.21, 3.49),
    (8.83, 5.06),
    (9.21, 6.92),
    (9.75, 8.13),
    (10.24, 8.33),
    (11.18, 7.84),
    (11.30, 8.02),
    (10.94, 8.35),
    (11.72, 8.53),
    (12.00, 8.95),
    (11.30, 9.77),
    (11.04, 10.51),
    (9.83, 11.09),
    (8.08, 10.48),
    (8.05, 9.97),
    (7.76, 9.53),
    (6.13, 9.43),
    (3.20, 10.07),
    (1.34, 9.80),
    (0.80, 10.38),
    (0.87, 11.17),
    (1.26, 11.54),
    (1.78, 11.51),
    (1.86, 11.30),
    (1.56, 10.86),
    (1.68, 10.65),
    (2.16, 10.89),
    (2.45, 11.33),
    (2.21, 11.82),
    (1.49, 12.15),
    (0.72, 11.89),
    (0.14, 11.00),
    (0.21, 10.19),
    (0.98, 9.07),
    (0.49, 7.83),
    (0.74, 5.13),
    (0.00, 3.69),
    (0.10, 1.25),
    (0.39, 0.79),
    (0.65, 0.78),
    (0.61, 2.93),
    (1.05, 3.93),
    (1.58, 4.52),
    (1.12, 3.25),
    (1.28, 2.17),
    (1.51, 1.10),
    (1.69, 0.92),
    (2.23, 0.95),
    (1.79, 1.82),
    (1.94, 3.45),
    (2.98, 5.96),
    (3.01, 6.75),
    (3.33, 6.40),
    (4.01, 6.65),
    (4.52, 6.45),
    (5.89, 5.14),
    (5.75, 1.63),
    (5.98, 0.29),
    (6.07, 0.05),
    (6.88, 0.00),
    (6.88, 0.00),
]
