"""Dog candidate 3 — Sitting dog full body — head up, tail behind, perky ears

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (11.500, 5.500),
    (11.500, 6.300),
    (10.800, 6.500),
    (10.300, 7.200),
    (10.000, 8.500),
    (9.400, 7.000),
    (9.000, 7.200),
    (8.600, 8.000),
    (8.400, 7.000),
    (7.000, 6.500),
    (5.000, 5.500),
    (3.500, 4.500),
    (2.500, 4.500),
    (1.500, 5.200),
    (1.000, 6.000),
    (1.500, 6.300),
    (2.500, 5.500),
    (3.300, 5.200),
    (3.500, 3.000),
    (3.500, 0.500),
    (3.500, 0.200),
    (5.000, 0.200),
    (5.000, 0.500),
    (4.800, 3.000),
    (7.000, 2.500),
    (9.000, 2.000),
    (9.500, 0.500),
    (9.500, 0.200),
    (10.700, 0.200),
    (10.700, 0.500),
    (10.500, 3.000),
    (10.800, 4.000),
    (11.000, 5.000),
    (11.500, 5.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (10.200, 6.800),
        (10.200, 6.600),
        (10.000, 6.700),
    ],
    [
        (11.200, 6.000),
        (11.400, 6.000),
    ],
]

METADATA = {"description": 'Sitting dog full body — head up, tail behind, perky ears', "source": "hand-crafted by tools/gen_candidates.py"}
