"""Dog candidate 4 — Dog face — perky pointed ears, eyes, nose, tongue

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (6.000, 8.000),
    (7.000, 8.000),
    (8.500, 11.000),
    (9.000, 7.500),
    (9.464, 7.000),
    (9.709, 6.498),
    (9.881, 5.968),
    (9.978, 5.418),
    (9.998, 4.860),
    (9.939, 4.305),
    (9.804, 3.764),
    (9.595, 3.247),
    (9.316, 2.763),
    (8.973, 2.323),
    (8.571, 1.936),
    (8.000, 2.500),
    (7.500, 1.500),
    (7.000, 1.000),
    (6.000, 0.500),
    (5.000, 1.000),
    (4.500, 1.500),
    (4.000, 2.500),
    (3.429, 1.936),
    (3.027, 2.323),
    (2.684, 2.763),
    (2.405, 3.247),
    (2.196, 3.764),
    (2.061, 4.305),
    (2.002, 4.860),
    (2.022, 5.418),
    (2.119, 5.968),
    (2.291, 6.498),
    (2.536, 7.000),
    (3.000, 7.500),
    (3.500, 11.000),
    (5.000, 8.000),
    (6.000, 8.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (5.000, 5.500),
        (4.943, 5.676),
        (4.793, 5.785),
        (4.607, 5.785),
        (4.457, 5.676),
        (4.400, 5.500),
        (4.457, 5.324),
        (4.607, 5.215),
        (4.793, 5.215),
        (4.943, 5.324),
        (5.000, 5.500),
    ],
    [
        (7.600, 5.500),
        (7.543, 5.676),
        (7.393, 5.785),
        (7.207, 5.785),
        (7.057, 5.676),
        (7.000, 5.500),
        (7.057, 5.324),
        (7.207, 5.215),
        (7.393, 5.215),
        (7.543, 5.324),
        (7.600, 5.500),
    ],
    [
        (5.600, 3.000),
        (6.400, 3.000),
        (6.000, 2.400),
        (6.000, 2.800),
    ],
    [
        (5.700, 0.700),
        (6.300, 0.700),
        (6.000, 1.500),
    ],
]

METADATA = {"description": 'Dog face — perky pointed ears, eyes, nose, tongue', "source": "hand-crafted by tools/gen_candidates.py"}
