"""Dog candidate 2 — Dog face — basset hound, droopy ears, tongue, eyes

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (6.000, 9.000),
    (6.000, 9.500),
    (6.488, 9.452),
    (6.957, 9.310),
    (7.389, 9.079),
    (7.768, 8.768),
    (8.079, 8.389),
    (8.310, 7.957),
    (8.452, 7.488),
    (8.500, 7.000),
    (9.000, 6.000),
    (9.500, 4.500),
    (9.166, 4.462),
    (8.849, 4.351),
    (8.565, 4.173),
    (8.327, 3.935),
    (8.149, 3.651),
    (8.038, 3.334),
    (8.000, 3.000),
    (8.038, 2.666),
    (8.149, 2.349),
    (8.327, 2.065),
    (8.565, 1.827),
    (8.849, 1.649),
    (9.166, 1.538),
    (9.500, 1.500),
    (9.000, 6.500),
    (8.000, 6.000),
    (7.500, 4.500),
    (7.000, 3.500),
    (6.500, 3.000),
    (5.500, 3.000),
    (5.000, 3.500),
    (4.500, 4.500),
    (4.000, 6.000),
    (3.000, 6.500),
    (2.500, 4.500),
    (2.834, 4.462),
    (3.151, 4.351),
    (3.435, 4.173),
    (3.673, 3.935),
    (3.851, 3.651),
    (3.962, 3.334),
    (4.000, 3.000),
    (3.962, 2.666),
    (3.851, 2.349),
    (3.673, 2.065),
    (3.435, 1.827),
    (3.151, 1.649),
    (2.834, 1.538),
    (2.500, 1.500),
    (3.000, 6.000),
    (3.500, 7.000),
    (3.548, 7.488),
    (3.690, 7.957),
    (3.921, 8.389),
    (4.232, 8.768),
    (4.611, 9.079),
    (5.043, 9.310),
    (5.512, 9.452),
    (6.000, 9.500),
    (6.000, 9.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (5.100, 7.500),
        (5.043, 7.676),
        (4.893, 7.785),
        (4.707, 7.785),
        (4.557, 7.676),
        (4.500, 7.500),
        (4.557, 7.324),
        (4.707, 7.215),
        (4.893, 7.215),
        (5.043, 7.324),
        (5.100, 7.500),
    ],
    [
        (7.500, 7.500),
        (7.443, 7.676),
        (7.293, 7.785),
        (7.107, 7.785),
        (6.957, 7.676),
        (6.900, 7.500),
        (6.957, 7.324),
        (7.107, 7.215),
        (7.293, 7.215),
        (7.443, 7.324),
        (7.500, 7.500),
    ],
    [
        (5.700, 4.500),
        (6.300, 4.500),
        (6.000, 3.900),
        (6.000, 4.200),
    ],
    [
        (5.800, 1.800),
        (6.200, 1.800),
        (6.000, 3.000),
    ],
]

METADATA = {"description": 'Dog face — basset hound, droopy ears, tongue, eyes', "source": "hand-crafted by tools/gen_candidates.py"}
