"""Write a GPX 1.1 file from a list of (lat, lon) points.

Garmin Connect, Strava, and most watch apps accept either <trk>/<trkpt> (track
points, treated as a recorded run) or <rte>/<rtept> (route points, treated as a
turn-by-turn navigation route). The architecture spec calls for <rte>/<rtept>.
We emit both a route and a track so the same file works for "follow this route"
and "import as planned activity" UIs.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Iterable, Tuple
from xml.sax.saxutils import escape


GPX_HEADER = '<?xml version="1.0" encoding="UTF-8"?>\n'
GPX_OPEN = (
    '<gpx version="1.1" creator="gps-art-runner" '
    'xmlns="http://www.topografix.com/GPX/1/1" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
    'xsi:schemaLocation="http://www.topografix.com/GPX/1/1 '
    'http://www.topografix.com/GPX/1/1/gpx.xsd">\n'
)


def write_gpx(
    path: str,
    polyline: Iterable[Tuple[float, float]],
    name: str = "Pig Run",
    description: str = "GPS-art route generated by gps-art-runner",
) -> None:
    points = list(polyline)
    if not points:
        raise ValueError("polyline is empty")

    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [GPX_HEADER, GPX_OPEN]
    lines.append(f"  <metadata><name>{escape(name)}</name>"
                 f"<desc>{escape(description)}</desc>"
                 f"<time>{now_iso}</time></metadata>\n")

    lines.append(f"  <rte>\n    <name>{escape(name)}</name>\n")
    for lat, lon in points:
        lines.append(f'    <rtept lat="{lat:.6f}" lon="{lon:.6f}"/>\n')
    lines.append("  </rte>\n")

    lines.append(f"  <trk>\n    <name>{escape(name)}</name>\n    <trkseg>\n")
    for lat, lon in points:
        lines.append(f'      <trkpt lat="{lat:.6f}" lon="{lon:.6f}"/>\n')
    lines.append("    </trkseg>\n  </trk>\n</gpx>\n")

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)
