"""Build KML 2.2 documents from a list of (lat, lon) points.

KML is what Google Earth / Google My Maps / Google Maps "Your Places"
imports natively. The path is encoded as a single Placemark containing a
LineString with `<coordinates>lon,lat,alt lon,lat,alt …</coordinates>`
(note: lon,lat order, opposite of GPX).

The route is styled with a thick blue line that matches the Folium preview
in `visualize.py`, so a route uploaded to My Maps looks the same colour as
the local HTML preview.
"""

from __future__ import annotations

from typing import Iterable, List, Tuple
from xml.sax.saxutils import escape

# KML colour format is AABBGGRR (alpha, blue, green, red). The hex below is
# opaque #1A73E8 (RGB) → e8731a in BGR with alpha ff → "ffe8731a", which
# matches the Folium polyline colour in visualize.py.
ROUTE_LINE_COLOR_ABGR = "ffe8731a"
ROUTE_LINE_WIDTH = 4

KML_HEADER = '<?xml version="1.0" encoding="UTF-8"?>\n'
KML_OPEN = '<kml xmlns="http://www.opengis.net/kml/2.2">\n'


def kml_to_string(
    polyline: Iterable[Tuple[float, float]],
    name: str = "DoodleRun Route",
    description: str = "GPS-art route generated by DoodleRun",
) -> str:
    """Render the polyline as a KML 2.2 document string.

    Args:
        polyline: ordered (lat, lon) tuples — same convention as gpx_export.
                  This function flips them to lon,lat,0 for KML internally.
    """
    points = list(polyline)
    if not points:
        raise ValueError("polyline is empty")

    coord_str = " ".join(f"{lon:.6f},{lat:.6f},0" for lat, lon in points)

    lines: List[str] = [KML_HEADER, KML_OPEN]
    lines.append("  <Document>\n")
    lines.append(f"    <name>{escape(name)}</name>\n")
    lines.append(f"    <description>{escape(description)}</description>\n")
    lines.append("    <Style id=\"routeStyle\">\n")
    lines.append("      <LineStyle>\n")
    lines.append(f"        <color>{ROUTE_LINE_COLOR_ABGR}</color>\n")
    lines.append(f"        <width>{ROUTE_LINE_WIDTH}</width>\n")
    lines.append("      </LineStyle>\n")
    lines.append("    </Style>\n")
    lines.append("    <Placemark>\n")
    lines.append(f"      <name>{escape(name)}</name>\n")
    lines.append("      <styleUrl>#routeStyle</styleUrl>\n")
    lines.append("      <LineString>\n")
    lines.append("        <tessellate>1</tessellate>\n")
    lines.append(f"        <coordinates>{coord_str}</coordinates>\n")
    lines.append("      </LineString>\n")
    lines.append("    </Placemark>\n")
    lines.append("  </Document>\n")
    lines.append("</kml>\n")
    return "".join(lines)


def write_kml(
    path: str,
    polyline: Iterable[Tuple[float, float]],
    name: str = "DoodleRun Route",
    description: str = "GPS-art route generated by DoodleRun",
) -> None:
    """Write the polyline as a KML 2.2 file at the given path."""
    text = kml_to_string(polyline, name=name, description=description)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
