"""Pig outline — derived from a kawaii cartoon-pig SVG.

Source SVG: freesvg.org "Outlined Pig" (https://freesvg.org/outlined-pig).
License: public domain (CC0 / freesvg.org).

Side-view kawaii pig: chubby round body, four stubby legs, tiny curly tail. The body+legs+tail are separate paths in the original cartoon, so the v4 pipeline shapely-unions the largest sub-paths into one continuous silhouette before tracing.

Generated by `tools/svg_to_shape.py --mode union` (or single, depending
on the source SVG). The shape file is the source of truth — hand edits
welcome — regeneration is not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

PIG_OUTLINE: List[Point] = [
    (9.98, 5.21),
    (9.26, 4.25),
    (8.15, 3.48),
    (9.73, 0.58),
    (8.96, 0.60),
    (8.51, 0.00),
    (7.90, 0.78),
    (8.05, 0.86),
    (6.91, 1.61),
    (6.17, 2.97),
    (5.60, 2.96),
    (5.39, 2.34),
    (5.66, 1.41),
    (4.96, 1.56),
    (4.43, 1.05),
    (3.86, 3.25),
    (3.30, 3.45),
    (2.87, 0.63),
    (2.27, 1.11),
    (1.55, 0.92),
    (1.65, 1.89),
    (1.30, 3.16),
    (1.53, 4.57),
    (0.49, 5.87),
    (0.00, 7.29),
    (0.10, 8.79),
    (0.81, 10.11),
    (0.18, 11.06),
    (0.20, 11.76),
    (0.73, 12.04),
    (1.28, 11.75),
    (1.01, 10.32),
    (2.53, 11.31),
    (4.30, 11.67),
    (6.24, 11.45),
    (8.16, 10.57),
    (9.72, 8.95),
    (10.29, 7.56),
    (10.32, 6.27),
    (12.00, 4.47),
    (11.41, 4.68),
    (11.86, 3.24),
    (11.68, 2.00),
    (11.93, 1.03),
    (11.21, 1.19),
    (10.67, 0.67),
    (9.59, 4.07),
    (11.21, 4.77),
    (10.11, 5.50),
    (9.98, 5.21),
]
