"""Pig outline — converted from a public-domain pig silhouette SVG.

Source SVG: Wikimedia Commons: Pig silhouette 02 (LadyofHats, public domain).
License: public domain (Wikimedia Commons).

Standing pig in side profile (4 legs visible). The body proportions make it read as 'pig' without an exaggerated cartoon tail.

Generated by `tools/svg_to_shape.py` (sampled by arc length, simplified
with Ramer-Douglas-Peucker, y-flipped from SVG y-down to math y-up).
Hand-edits welcome — this file is the source of truth, regeneration is
not part of the build.
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

PIG_OUTLINE: List[Point] = [
    (11.31, 4.36),
    (10.62, 4.94),
    (9.38, 5.33),
    (4.45, 5.40),
    (0.31, 4.25),
    (0.04, 4.00),
    (0.89, 3.71),
    (0.00, 3.50),
    (0.22, 2.74),
    (1.28, 2.26),
    (3.90, 1.83),
    (4.17, 1.23),
    (3.98, 0.12),
    (4.51, 0.13),
    (4.79, 0.52),
    (5.27, 0.62),
    (5.46, 1.99),
    (5.94, 1.57),
    (6.14, 1.85),
    (6.66, 1.53),
    (8.64, 1.69),
    (9.19, 1.43),
    (9.52, 1.63),
    (9.55, 1.07),
    (8.94, 0.27),
    (9.15, 0.00),
    (9.87, 0.09),
    (10.65, 1.12),
    (10.68, 1.91),
    (11.32, 3.03),
    (11.34, 3.93),
    (12.00, 3.96),
    (11.31, 4.36),
    (11.31, 4.36),
]
