"""Pig candidate 4 — Side-profile pig with one prominent floppy round ear

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (12.000, 3.500),
    (12.000, 4.400),
    (11.300, 4.600),
    (10.800, 5.200),
    (10.400, 5.700),
    (9.474, 6.280),
    (9.136, 6.171),
    (8.840, 5.975),
    (8.608, 5.705),
    (8.458, 5.383),
    (8.400, 5.032),
    (8.440, 4.679),
    (8.574, 4.350),
    (8.792, 4.069),
    (9.078, 3.858),
    (9.411, 3.733),
    (9.765, 3.702),
    (10.114, 3.768),
    (10.432, 3.926),
    (10.696, 4.164),
    (10.600, 5.300),
    (10.800, 5.600),
    (10.500, 6.000),
    (8.500, 6.100),
    (5.000, 6.000),
    (3.500, 5.800),
    (2.800, 6.400),
    (2.200, 6.000),
    (2.600, 5.400),
    (3.200, 5.600),
    (3.800, 5.200),
    (3.800, 3.000),
    (3.800, 0.400),
    (3.800, 0.200),
    (5.000, 0.200),
    (5.000, 0.400),
    (4.900, 1.800),
    (6.500, 1.700),
    (9.000, 1.700),
    (9.500, 1.900),
    (9.500, 0.400),
    (9.500, 0.200),
    (10.700, 0.200),
    (10.700, 0.400),
    (10.500, 1.900),
    (11.200, 2.400),
    (11.700, 3.000),
    (12.000, 3.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (11.400, 3.700),
        (11.400, 3.900),
        (11.400, 3.700),
    ],
    [
        (11.400, 4.000),
        (11.400, 4.200),
        (11.400, 4.000),
    ],
]

METADATA = {"description": 'Side-profile pig with one prominent floppy round ear', "source": "hand-crafted by tools/gen_candidates.py"}
