"""Pig candidate 2 — Pig face — round flappy ears, snout disc, nostril dots

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (3.000, 8.000),
    (3.600, 9.000),
    (3.551, 9.395),
    (3.405, 9.765),
    (3.173, 10.088),
    (2.868, 10.344),
    (2.510, 10.517),
    (2.120, 10.596),
    (1.722, 10.576),
    (1.342, 10.458),
    (1.002, 10.251),
    (0.725, 9.966),
    (0.526, 9.621),
    (0.418, 9.238),
    (0.408, 8.841),
    (0.496, 8.453),
    (1.500, 8.500),
    (1.200, 7.500),
    (1.218, 5.918),
    (1.200, 5.458),
    (1.226, 4.998),
    (1.296, 4.543),
    (1.410, 4.097),
    (1.565, 3.663),
    (1.762, 3.247),
    (1.997, 2.851),
    (2.270, 2.479),
    (2.576, 2.136),
    (2.915, 1.823),
    (4.200, 1.500),
    (6.000, 1.000),
    (7.800, 1.500),
    (9.085, 1.823),
    (9.364, 2.076),
    (9.623, 2.351),
    (9.859, 2.645),
    (10.071, 2.956),
    (10.258, 3.284),
    (10.418, 3.624),
    (10.552, 3.977),
    (10.657, 4.339),
    (10.734, 4.708),
    (10.782, 5.082),
    (10.800, 7.500),
    (10.500, 8.500),
    (9.000, 8.000),
    (11.504, 8.453),
    (11.592, 8.841),
    (11.582, 9.238),
    (11.474, 9.621),
    (11.275, 9.966),
    (10.998, 10.251),
    (10.658, 10.458),
    (10.278, 10.576),
    (9.880, 10.596),
    (9.490, 10.517),
    (9.132, 10.344),
    (8.827, 10.088),
    (8.595, 9.765),
    (8.449, 9.395),
    (8.400, 9.000),
    (9.000, 8.000),
    (7.500, 7.600),
    (7.400, 4.800),
    (7.316, 5.279),
    (7.072, 5.700),
    (6.700, 6.012),
    (6.243, 6.179),
    (5.757, 6.179),
    (5.300, 6.012),
    (4.928, 5.700),
    (4.684, 5.279),
    (4.600, 4.800),
    (4.684, 4.321),
    (4.928, 3.900),
    (5.300, 3.588),
    (5.757, 3.421),
    (6.243, 3.421),
    (6.700, 3.588),
    (7.072, 3.900),
    (7.316, 4.321),
    (7.400, 4.800),
    (4.500, 7.600),
    (3.000, 8.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (5.500, 4.500),
        (5.400, 4.900),
        (5.500, 4.500),
    ],
    [
        (6.500, 4.500),
        (6.600, 4.900),
        (6.500, 4.500),
    ],
]

METADATA = {"description": 'Pig face — round flappy ears, snout disc, nostril dots', "source": "hand-crafted by tools/gen_candidates.py"}
