"""Pig candidate 3 — Chubby seated pig — curly tail, ear bump, nostril dots

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (11.500, 4.500),
    (11.500, 5.500),
    (10.800, 5.700),
    (10.200, 6.600),
    (10.386, 6.844),
    (10.383, 7.172),
    (10.263, 7.477),
    (10.042, 7.719),
    (9.748, 7.865),
    (9.422, 7.897),
    (9.105, 7.809),
    (8.842, 7.614),
    (8.666, 7.337),
    (8.600, 7.016),
    (8.654, 6.692),
    (9.000, 6.800),
    (7.750, 7.531),
    (7.299, 7.750),
    (6.821, 7.902),
    (6.327, 7.985),
    (5.826, 7.996),
    (5.328, 7.935),
    (4.844, 7.804),
    (4.384, 7.605),
    (3.957, 7.342),
    (3.572, 7.021),
    (3.237, 6.648),
    (2.958, 6.231),
    (2.742, 5.779),
    (2.593, 5.300),
    (2.513, 4.805),
    (2.400, 4.700),
    (2.000, 5.200),
    (1.600, 4.800),
    (2.000, 4.400),
    (2.400, 4.500),
    (2.513, 4.805),
    (2.502, 4.385),
    (2.541, 3.968),
    (2.629, 3.557),
    (2.766, 3.161),
    (2.950, 2.783),
    (3.177, 2.430),
    (3.445, 2.107),
    (3.750, 1.819),
    (4.200, 1.000),
    (4.200, 0.400),
    (5.400, 0.400),
    (5.400, 1.500),
    (7.400, 1.500),
    (7.600, 0.800),
    (7.600, 0.400),
    (8.800, 0.400),
    (8.800, 1.500),
    (8.582, 2.689),
    (8.836, 2.544),
    (9.113, 2.448),
    (9.402, 2.403),
    (9.695, 2.412),
    (9.981, 2.474),
    (10.251, 2.587),
    (10.496, 2.748),
    (10.708, 2.950),
    (10.879, 3.188),
    (11.004, 3.453),
    (11.000, 4.400),
    (11.500, 4.500),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (11.000, 4.800),
        (11.000, 5.000),
        (11.000, 4.800),
    ],
    [
        (11.000, 5.300),
        (11.000, 5.500),
        (11.000, 5.300),
    ],
]

METADATA = {"description": 'Chubby seated pig — curly tail, ear bump, nostril dots', "source": "hand-crafted by tools/gen_candidates.py"}
