"""Pig candidate 5 — Pig face 3/4 view — big snout disc, two round ears on top

Generated by `tools/gen_candidates.py`. Hand-crafted in Python pending
ingestion of source SVGs through `tools/svg_to_shape.py --with-interior`.

Format follows the standard shape-file interface (see `prototype/shapes.py`):
- OUTLINE: closed silhouette polyline.
- INTERIOR_FEATURES: list of polylines for interior detail strokes
  (whiskers, nostrils, eyes, etc.) — anchored to the outline at trace time
  by `compose_route()`.
- METADATA: free-form dict (description, source, license, …).
"""

from __future__ import annotations

from typing import List

from shape_utils import Point

OUTLINE: List[Point] = [
    (6.000, 10.000),
    (6.600, 10.000),
    (6.648, 10.362),
    (6.788, 10.700),
    (7.010, 10.990),
    (7.300, 11.212),
    (7.638, 11.352),
    (8.000, 11.400),
    (8.362, 11.352),
    (8.700, 11.212),
    (8.990, 10.990),
    (9.212, 10.700),
    (9.352, 10.362),
    (9.400, 10.000),
    (9.214, 8.830),
    (9.665, 8.401),
    (10.060, 7.919),
    (10.391, 7.391),
    (10.654, 6.827),
    (10.845, 6.234),
    (10.961, 5.622),
    (11.000, 5.000),
    (10.961, 4.378),
    (10.845, 3.766),
    (10.654, 3.173),
    (10.391, 2.609),
    (10.060, 2.081),
    (9.665, 1.599),
    (9.214, 1.170),
    (6.000, -0.200),
    (2.786, 1.170),
    (2.335, 1.599),
    (1.940, 2.081),
    (1.609, 2.609),
    (1.346, 3.173),
    (1.155, 3.766),
    (1.039, 4.378),
    (1.000, 5.000),
    (1.039, 5.622),
    (1.155, 6.234),
    (1.346, 6.827),
    (1.609, 7.391),
    (1.940, 7.919),
    (2.335, 8.401),
    (2.786, 8.830),
    (2.600, 10.000),
    (2.648, 9.638),
    (2.788, 9.300),
    (3.010, 9.010),
    (3.300, 8.788),
    (3.638, 8.648),
    (4.000, 8.600),
    (4.362, 8.648),
    (4.700, 8.788),
    (4.990, 9.010),
    (5.212, 9.300),
    (5.352, 9.638),
    (5.400, 10.000),
    (6.000, 10.000),
]

INTERIOR_FEATURES: List[List[Point]] = [
    [
        (7.800, 3.500),
        (7.663, 4.189),
        (7.273, 4.773),
        (6.689, 5.163),
        (6.000, 5.300),
        (5.311, 5.163),
        (4.727, 4.773),
        (4.337, 4.189),
        (4.200, 3.500),
        (4.337, 2.811),
        (4.727, 2.227),
        (5.311, 1.837),
        (6.000, 1.700),
        (6.689, 1.837),
        (7.273, 2.227),
        (7.663, 2.811),
        (7.800, 3.500),
    ],
    [
        (5.400, 3.300),
        (5.300, 3.500),
        (5.400, 3.300),
    ],
    [
        (6.600, 3.300),
        (6.700, 3.500),
        (6.600, 3.300),
    ],
]

METADATA = {"description": 'Pig face 3/4 view — big snout disc, two round ears on top', "source": "hand-crafted by tools/gen_candidates.py"}
